# Generated by Django 3.0 on 2020-01-13 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='faculty_details',
        ),
    ]
