# Generated by Django 3.0 on 2020-01-13 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0003_faculty_details'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='faculty_details',
            table='faculty_details',
        ),
    ]
